-- Q1. From the table SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS, find the top 5 customers who placed the highest number of orders in 1995.


USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1;


SELECT *
FROM ORDERS
LIMIT 15;

SELECT COUNT(*), COUNT(O_CUSTKEY)
FROM ORDERS;

SELECT O_CUSTKEY, O_ORDERDATE, COUNT(O_ORDERKEY) AS NO_OF_ORDERS
FROM ORDERS
GROUP BY O_CUSTKEY, O_ORDERDATE
HAVING O_ORDERDATE BETWEEN '1995-01-01' AND '1995-12-31'
ORDER BY NO_OF_ORDERS DESC
LIMIT 5;

WITH CTE AS
(
SELECT O_CUSTKEY, COUNT(*) AS NO_OF_ORDERS, SUM(O_TOTALPRICE) AS TOT_PRCE
FROM ORDERS
GROUP BY O_CUSTKEY
ORDER BY NO_OF_ORDERS DESC, TOT_PRCE DESC
),
CTE2 AS
(
SELECT *,
RANK() OVER (PARTITION BY NO_OF_ORDERS ORDER BY TOT_PRCE DESC) AS RNK
FROM CTE
)
SELECT *
FROM CTE2
WHERE RNK = 1
-- LIMIT 1
;


WITH CTE AS
(
SELECT O_CUSTKEY, COUNT(*) AS NO_OF_ORDERS, SUM(O_TOTALPRICE) AS TOT_PRCE
FROM ORDERS
GROUP BY O_CUSTKEY
ORDER BY NO_OF_ORDERS DESC, TOT_PRCE DESC
)
SELECT *
FROM CTE
qualify RANK() OVER (PARTITION BY NO_OF_ORDERS ORDER BY TOT_PRCE DESC) = 1
;

-- Q2. Using CUSTOMER and ORDERS, find customers who have never placed any orders.

SELECT DISTINCT (O_CUSTKEY)
FROM ORDERS;

SELECT *
FROM CUSTOMER
WHERE C_CUSTKEY NOT IN 
(
SELECT DISTINCT (O_CUSTKEY)
FROM ORDERS
);


SELECT C.*, O.*
FROM CUSTOMER C
LEFT JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
WHERE O.O_CUSTKEY IS NULL;



SELECT *
FROM ORDERS
WHERE O_CUSTKEY = 40146;


-- Q3. From LINEITEM, find the total revenue per shipmode where the order was shipped later than the commit date.

SELECT *
FROM LINEITEM
LIMIT 10;

SELECT L_SHIPMODE, SUM(L_EXTENDEDPRICE) AS TOT_REVENUE
FROM LINEITEM
WHERE L_SHIPDATE > L_COMMITDATE
GROUP BY L_SHIPMODE;

-- Q4. Using LINEITEM, calculate the running total of revenue for each order (partition by ORDERKEY, order by LINENUMBER).

SELECT L_ORDERKEY,L_EXTENDEDPRICE,L_LINENUMBER,
 SUM(L_EXTENDEDPRICE) OVER (PARTITION BY L_ORDERKEY ORDER BY L_LINENUMBER ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) running_total
FROM LINEITEM;

-- Q5. From ORDERS, find the second highest order total per customer (use RANK / DENSE_RANK).

WITH CTE AS
(
SELECT O_CUSTKEY,COUNT(*) AS NO_OF_ORDERS
FROM ORDERS
GROUP BY O_CUSTKEY
ORDER BY NO_OF_ORDERS DESC
)
SELECT *, 
RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS RNK,
DENSE_RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS D_RNK
FROM CTE
QUALIFY D_RNK =2;

-- 3RD HIGHEST CUSTOMER YEAR WISE PARTITION

WITH CTE AS

(
SELECT *,
EXTRACT(year FROM O_ORDERDATE) AS YEAR
FROM ORDERS
),
CTEE AS
(
SELECT O_CUSTKEY, YEAR, COUNT(*) AS NO_OF_ORDERS
FROM CTE
GROUP BY O_CUSTKEY, YEAR
ORDER BY NO_OF_ORDERS DESC
)

SELECT O_CUSTKEY, NO_OF_ORDERS, YEAR,
RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS RNK,
DENSE_RANK() OVER (ORDER BY NO_OF_ORDERS DESC) AS D_RNK
FROM CTEE
QUALIFY D_RNK = 3
ORDER BY YEAR
;

SELECT 
FROM ORDERS;


-- From ORDERS, find the FIFTH highest totalPRICE per customer

WITH CTE AS
(
SELECT *, EXTRACT (year FROM O_ORDERDATE) AS YEAR
FROM ORDERS
),

CTE2 AS

(
SELECT O_CUSTKEY, YEAR, SUM(O_TOTALPRICE) AS TOT_PRCE
FROM CTE
GROUP BY O_CUSTKEY, YEAR
ORDER BY TOT_PRCE DESC
)
SELECT *,
RANK() OVER (ORDER BY TOT_PRCE DESC) AS RNK,
DENSE_RANK() OVER (ORDER BY TOT_PRCE DESC)AS D_RNK
FROM CTE2
QUALIFY DENSE_RANK() OVER (ORDER BY TOT_PRCE DESC) = 5
;

-- Q1.Find the top 3 customers (by revenue) in each nation.

WITH CTE AS
(
SELECT C.C_CUSTKEY,L.L_EXTENDEDPRICE,L.L_DISCOUNT,N.N_NATIONKEY,N.N_NAME
FROM CUSTOMER C
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
JOIN LINEITEM L ON L.L_ORDERKEY= O.O_ORDERKEY
),

CTE2 AS
(
SELECT CTE.N_NAME, CTE.C_CUSTKEY, SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.N_NAME, CTE.C_CUSTKEY
ORDER BY REVENUE DESC
)
SELECT *,
ROW_NUMBER() OVER (PARTITION BY CTE2.N_NAME ORDER BY REVENUE DESC) AS R_N
FROM CTE2
QUALIFY R_N = 1 OR R_N =2 OR R_N =3;

-- Q2.For each customer, calculate their cumulative spend over time.

WITH CTE AS
(
SELECT C.C_CUSTKEY,L.L_EXTENDEDPRICE,L.L_DISCOUNT,O.O_ORDERDATE
FROM CUSTOMER C
JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
JOIN LINEITEM L ON L.L_ORDERKEY=O.O_ORDERKEY
),

CTE2 AS

(
SELECT CTE.C_CUSTKEY, CTE.O_ORDERDATE, SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.C_CUSTKEY, CTE.O_ORDERDATE
)

SELECT *,

SUM(REVENUE) OVER (PARTITION BY CTE2.C_CUSTKEY ORDER BY CTE2.O_ORDERDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) RUNNING_TOTAL,
FROM CTE2;

-- Q3.For each customer, find their first and last order date and total spend in those orders.

WITH CTE AS
(
SELECT O_CUSTKEY,  O_ORDERKEY, MIN(O_ORDERDATE)AS FIRST_ORD_DATE,MAX(O_ORDERDATE) AS LAST_ORD_DATE
FROM ORDERS
GROUP BY O_CUSTKEY, O_ORDERKEY
)
SELECT O_CUSTKEY,  O_ORDERKEY,FIRST_ORD_DATE,LAST_ORD_DATE, 
FROM CTE 
JOIN LINEITEM L ON CTE.O_ORDERKEY = L.L_ORDERKEY;


SELECT *
FROM ORDERS
LIMIT 10;

-- Q3.For each customer, find their first and last order date and total spend in those orders.

WITH CTE AS
(
SELECT O_CUSTKEY, O_ORDERDATE, O_TOTALPRICE,
ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS R_N
FROM ORDERS
)
SELECT O_CUSTKEY, O_ORDERDATE, O_TOTALPRICE,R_N
FIRST_VALUE(O_TOTALPRICE)  OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE
         ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS FIRST_VAL,
LAST_VALUE(O_TOTALPRICE)   OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE
         ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS LAST_VAL
FROM CTE;

SELECT O_CUSTKEY,O_ORDERDATE,O_TOTALPRICE,
ROW_NUMBER() OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS R_N,
LEAD(O_TOTALPRICE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS L_D,
LAG(O_TOTALPRICE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS L_G,
FIRST_VALUE(O_ORDERDATE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS F_DATE,
LAST_VALUE(O_ORDERDATE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS L_DATE,
FIRST_VALUE(O_TOTALPRICE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS F_V,
LAST_VALUE(O_TOTALPRICE) OVER(PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS L_V
FROM ORDERS
-- WHERE O_CUSTKEY = 139136
QUALIFY R_N = 1
ORDER BY O_ORDERDATE
;



SELECT O_CUSTKEY,O_ORDERDATE,O_TOTALPRICE,
LAG(O_ORDERDATE) OVER(ORDER BY O_ORDERDATE) AS DIFF, (O_ORDERDATE - DIFF) AS DIFF_DATE
FROM ORDERS
ORDER BY O_ORDERDATE;

-- Q1.FIND TOP 5 CUSTOMERS BY REVENUE

WITH CTE AS
(
SELECT O_CUSTKEY, L_DISCOUNT,L_EXTENDEDPRICE,(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REV
FROM ORDERS O
JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
),
CTE2 AS
(
SELECT O_CUSTKEY, SUM(REV) AS REVENUE
FROM CTE
GROUP BY O_CUSTKEY
)
SELECT O_CUSTKEY, REVENUE,
DENSE_RANK() OVER (ORDER BY CTE2.REVENUE DESC)AS D_RNK
FROM CTE2
QUALIFY D_RNK<=5
;

-- Q2. For each customer, show a running total revenue by order date.

WITH CTE AS
(
SELECT O.O_CUSTKEY,O.O_ORDERDATE,O.O_ORDERKEY,L.L_EXTENDEDPRICE,L.L_DISCOUNT
FROM ORDERS O
JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
),

CTE2 AS
(
SELECT CTE.O_CUSTKEY, CTE.O_ORDERDATE, SUM(L_EXTENDEDPRICE * (1- L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.O_CUSTKEY, CTE.O_ORDERDATE
)

SELECT CTE2.O_CUSTKEY, CTE2.O_ORDERDATE, CTE2.REVENUE,
SUM(REVENUE) OVER (PARTITION BY CTE2.O_CUSTKEY ORDER BY CTE2.O_ORDERDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total
 
FROM CTE2;


-- Q3.For each customer, calculate days between consecutive orders.

WITH CTE AS
(
SELECT O_CUSTKEY,O_ORDERKEY,O_ORDERDATE,
LAG(O_ORDERDATE) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS L_G
FROM ORDERS
)
SELECT O_CUSTKEY,O_ORDERKEY,O_ORDERDATE,L_G,( O_ORDERDATE - L_G) AS DIFF_DAYS
FROM CTE
;

-- Q4.Find the top 3 suppliers in each region by revenue

WITH CTE AS
(
SELECT S.S_SUPPKEY, R.R_REGIONKEY, L.L_DISCOUNT, L.L_EXTENDEDPRICE
FROM SUPPLIER S
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
JOIN LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
),

CTE2 AS
(
SELECT CTE.S_SUPPKEY, CTE.R_REGIONKEY, SUM(L_EXTENDEDPRICE * (1- L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.S_SUPPKEY, CTE.R_REGIONKEY
ORDER BY CTE.R_REGIONKEY
)
SELECT CTE2.S_SUPPKEY, CTE2.R_REGIONKEY, REVENUE,

RANK() OVER (PARTITION BY CTE2.R_REGIONKEY ORDER BY CTE2.REVENUE DESC) AS RNK

FROM CTE2
QUALIFY RNK<=3
;
-- Q5.Find the year-over-year sales growth for each region.

WITH CTE AS
(
SELECT R.R_REGIONKEY, EXTRACT(YEAR FROM O_ORDERDATE) AS YEAR,  L.L_DISCOUNT, L.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
JOIN SUPPLIER S ON S.S_SUPPKEY = L.L_SUPPKEY
JOIN NATION N ON N.N_NATIONKEY = S.S_NATIONKEY
JOIN REGION R ON R.R_REGIONKEY = N.N_REGIONKEY
),

CTE2 AS
(
SELECT CTE.R_REGIONKEY, CTE.YEAR, SUM(L_EXTENDEDPRICE * (1- L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY CTE.R_REGIONKEY,CTE.YEAR
),
CTE3 AS
(
SELECT CTE2.R_REGIONKEY,YEAR, REVENUE,
LAG(REVENUE) OVER (PARTITION BY CTE2.R_REGIONKEY ORDER BY YEAR) AS PREV_Y_REV
FROM CTE2
)
SELECT CTE3.R_REGIONKEY, YEAR, REVENUE, (((REVENUE - PREV_Y_REV)/ PREV_Y_REV )*100) AS DIFF_YEAR
FROM CTE3;

-- Q6.Find customers whose spending increased every year.

WITH CTE AS

(
SELECT O_CUSTKEY, EXTRACT(YEAR FROM O_ORDERDATE) AS CURR_YEAR, (L_EXTENDEDPRICE * (1- L_DISCOUNT)) AS REV
FROM ORDERS O
JOIN LINEITEM L ON O_ORDERKEY = L_ORDERKEY
),
CTE2 AS
(
SELECT O_CUSTKEY, CURR_YEAR, SUM(REV) AS REVENUE
FROM CTE
GROUP BY O_CUSTKEY, CURR_YEAR
),

CTE3 AS
(
SELECT O_CUSTKEY, CURR_YEAR, REVENUE,
LAG(REVENUE) OVER (PARTITION BY O_CUSTKEY ORDER BY CURR_YEAR) AS PREV_REVENUE, 
(((REVENUE - PREV_REVENUE)/ PREV_REVENUE)*100) AS DIFF_GROWTH,
CASE
    WHEN DIFF_GROWTH > 0 THEN '1'
    WHEN DIFF_GROWTH < 0 THEN '0'
    ELSE '1'
END AS CHECKK
FROM CTE2
)
select
*,
SUM(CHECKK) OVER (PARTITION BY O_CUSTKEY ORDER BY CURR_YEAR ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS _sum,
count(*) OVER (PARTITION BY O_CUSTKEY ORDER BY CURR_YEAR ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS _count,
_count = _sum  as _flag,
row_number() OVER (PARTITION BY O_CUSTKEY ORDER BY CURR_YEAR) AS r_no,
from cte3
qualify _flag = true and r_no=1;

select *
from cte4
where o_custkey = 89960;

SELECT O_CUSTKEY, COUNT(*), SUM(CHECKK)
FROM CTE3
GROUP BY O_CUSTKEY
HAVING COUNT(*) = SUM(CHECKK) + 1 ;


-- Q7.Find the 90th percentile order revenue for each region.

WITH CTE AS
(
SELECT R.R_REGIONKEY, L.L_EXTENDEDPRICE,L.L_DISCOUNT
FROM LINEITEM L 
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN NATION N ON N.N_NATIONKEY = S.S_NATIONKEY
JOIN REGION R ON R.R_REGIONKEY = N.N_REGIONKEY
),
CTE2 AS
(
SELECT R_REGIONKEY, SUM(L_EXTENDEDPRICE * (1- L_DISCOUNT)) AS REVENUE
FROM CTE
GROUP BY R_REGIONKEY
ORDER BY REVENUE
),
CTE3 AS
(SELECT *, 
SUM(REVENUE) OVER (ORDER BY REVENUE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS REV_SUM,
REVENUE/REV_SUM AS REV_DIV,
FROM CTE2
ORDER BY REV_DIV
)
SELECT *,
SUM(REV_DIV) OVER (ORDER BY REVENUE ) AS REV_NEW
FROM CTE3;


-- Q8.Find the customer–supplier pair with the highest number of transactions.

WITH CTE AS

(
SELECT C.C_CUSTKEY,S.S_SUPPKEY
FROM CUSTOMER C
JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
JOIN LINEITEM L ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN SUPPLIER S ON S.S_SUPPKEY = L.L_SUPPKEY
)
SELECT C_CUSTKEY, S_SUPPKEY, COUNT(*) AS NO_ORDERS
FROM CTE
GROUP BY C_CUSTKEY, S_SUPPKEY
ORDER BY NO_ORDERS DESC;

-- Q9.Find customers who ordered in every month of a given year (say 1995).

WITH CTE AS
(
SELECT O_CUSTKEY, EXTRACT(YEAR FROM O_ORDERDATE) AS _YEAR, EXTRACT(MONTH FROM O_ORDERDATE)AS _MONTH, O_ORDERKEY
FROM ORDERS
WHERE _YEAR = 1995
),
CTE2 AS
(
SELECT O_CUSTKEY, _MONTH, COUNT(*) AS NO_ORDERS
FROM CTE
GROUP BY O_CUSTKEY, _MONTH
ORDER BY _MONTH
)
SELECT O_CUSTKEY, COUNT(*)
FROM CTE2
GROUP BY O_CUSTKEY
-- HAVING COUNT(*) = 12
ORDER BY 2 DESC;
;
 

SELECT O_CUSTKEY, COUNT(DISTINCT  TO_VARCHAR(O_ORDERDATE, 'yyyy-MM')) AS _COUNT
FROM ORDERS
WHERE YEAR(O_ORDERDATE) = 1995
GROUP BY O_CUSTKEY
ORDER BY 2 DESC;

-- Q10.Find products that were ordered only once ever across all customers.

WITH CTE AS
(
    SELECT O_CUSTKEY, L_LINENUMBER
    FROM ORDERS O 
    JOIN LINEITEM L ON L.L_ORDERKEY = O.O_ORDERKEY
)

SELECT  L_LINENUMBER, COUNT(*) AS _COUNT
FROM CTE
GROUP BY L_LINENUMBER
ORDER BY _COUNT;
-- HAVING COUNT(*) =1
;

-- Q11.Identify customers who placed at least two consecutive orders within 7 days

WITH CTE AS
(
    SELECT O_CUSTKEY,O_ORDERKEY,O_ORDERDATE,
    LAG(O_ORDERDATE) OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE)AS LAG_DATE, (O_ORDERDATE -  LAG_DATE) AS DIFF_DATE
    FROM ORDERS
)
SELECT DISTINCT (O_CUSTKEY)
FROM CTE
WHERE DIFF_DATE=7;

-- Q12.For each year, find the supplier with the highest total revenue.

WITH CTE AS
(
SELECT EXTRACT (YEAR FROM O_ORDERDATE) AS _YEAR, S.S_SUPPKEY, O_TOTALPRICE
FROM ORDERS O
JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
),
CTE2 AS
(
SELECT _YEAR, S_SUPPKEY, SUM(O_TOTALPRICE) AS REVENUE
FROM CTE
GROUP BY _YEAR, S_SUPPKEY
ORDER BY _YEAR, REVENUE DESC
)
SELECT *, DENSE_RANK () OVER (PARTITION BY _YEAR ORDER BY REVENUE DESC) AS D_RNK
FROM CTE2
QUALIFY D_RNK = 1
ORDER BY _YEAR;

-- Q13.Find the percentage contribution of each nation’s suppliers to the total revenue in their region.

WITH CTE AS
    
    (

    SELECT N.N_NAME,R.R_NAME, R.R_REGIONKEY, S.S_SUPPKEY, (L.L_EXTENDEDPRICE * (1-L.L_DISCOUNT)) AS REVENUE_
    FROM LINEITEM L
    JOIN SUPPLIER S ON S.S_SUPPKEY = L.L_SUPPKEY
    JOIN NATION N ON N.N_NATIONKEY = S.S_NATIONKEY
    JOIN REGION R ON R.R_REGIONKEY = N.N_REGIONKEY

    ),
    
CTE2 AS

    (
    SELECT N_NAME,R_REGIONKEY,R_NAME, S_SUPPKEY, SUM(REVENUE_) AS REVENUE_SUM
    FROM CTE
    GROUP BY N_NAME, R_REGIONKEY,R_NAME, S_SUPPKEY
    )

SELECT *,
SUM(REVENUE_SUM) OVER (PARTITION BY R_REGIONKEY) AS TOTAL_REVENUE, ((REVENUE_SUM / TOTAL_REVENUE) *100) AS PERCENT_CONTRBUTN
FROM CTE2
ORDER BY N_NAME, R_REGIONKEY,R_NAME,REVENUE_SUM;

-- Q14.Find the longest streak of consecutive order days for each customer.

WITH CTE AS(
    SELECT DISTINCT O_CUSTKEY, O_ORDERDATE
    FROM ORDERS
    ),
    
CTE2 AS
    (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY O_ORDERDATE) AS R_N, 
    (O_ORDERDATE - R_N) AS NEW_DATE
    FROM CTE
    ),

CTE3 AS
    (
    SELECT O_CUSTKEY, NEW_DATE, MIN(O_ORDERDATE), MAX(O_ORDERDATE) , COUNT(*) AS COUNT_
    FROM CTE2
    WHERE O_CUSTKEY = 12646
    GROUP BY O_CUSTKEY, NEW_DATE
    ORDER BY COUNT_ DESC
    )

    -- SELECT *, ROW_NUMBER() OVER (PARTITION BY O_CUSTKEY ORDER BY COUNT_ DESC) AS R_NN
    -- FROM CTE3
    -- QUALIFY R_NN = 1

    -- SELECT O_CUSTKEY, MAX(COUNT_)
    -- FROM CTE3
    -- GROUP BY O_CUSTKEY
    
SELECT *
FROM CTE3;

-- Q15.Find the customer who spent the most in their very first order.

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
select* from part;
SELECT * FROM PARTSUPP;
-- Q16.Find orders that contain all products from a particular category.
-- Q17.Find the top 5 customers by revenue contribution in each region and year
-- q18.Find the product that had the largest price increase between any two consecutive years.

select *
from part
limit 10;

select distinct p_name
from part
where p_type = 'MEDIUM BURNISHED COPPER';