-- Q2. Using CUSTOMER and ORDERS, find customers who have never placed any orders.

USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1;

SELECT C.C_CUSTKEY, C.C_NAME
FROM CUSTOMER C
LEFT JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
WHERE O.O_CUSTKEY IS NULL;
